version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - yakky
  ignore:
  - dependency-name: coverage
    versions:
    - ">= 5.0.a, < 5.1"
