version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - pdf

python:
  version: 3.7
  install:
    - requirements: requirements-test.txt
    - method: pip
      path: .
      extra_requirements:
         - docs
  system_packages: false
